name: basir
description: Blind Assist App helping visually impaired users understand their surroundings.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.0
  google_mlkit_object_detection: ^0.9.0
  google_mlkit_text_recognition: ^0.11.0
  path_provider: ^2.1.4
  http: ^1.2.1

  # Accessibility helpers
  provider: ^6.1.2

  # Needed for vibration feedback via system services
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
